---
# tasks file for vector-role
# VECTOR
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/{{ vector_package }}-{{ vector_version }}-1.x86_64.rpm"
    dest: "./{{ vector_package }}-{{ vector_version }}-1.x86_64.rpm"
    validate_certs: false
    mode: "u+rwx"
- name: Install vector distrib
  ansible.builtin.yum:
    name: ./{{ vector_package }}-{{ vector_version }}-1.x86_64.rpm
- name: Deploy vector config
  ansible.builtin.template:
    src: templates/vector.toml.j2
    dest: /etc/vector/vector.toml
    mode: "u+rwx"
  notify: Start vector service